global:
  scrape_interval: 20s

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets:
          - host.docker.internal:9090
  - job_name: scrapper
    static_configs:
      - targets:
          - host.docker.internal:8081
  - job_name: bot
    static_configs:
      - targets:
          - host.docker.internal:8091
