app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 1m
  database-access-type: jdbc
  use-queue: true
  topic: "updates-topic"
  producer-client-id: demo-producer

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: "localhost:29092"
    producer:
      properties:
        spring.json.add.type.headers: false

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
      exposure:
        include: [ "prometheus", "health", "info" ]
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: "/swagger-ui"

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 100ms
        enable-exponential-backoff: true
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.reactive.function.client.WebClientRequestException
    instances:
      updatesPost:
        base-config: default
      fetchRepo:
        base-config: default
      fetchCommitsSince:
        base-config: default
      fetchPullRequestsSince:
        base-config: default
      fetchQuestion:
        base-config: default
      fetchAnswersSince:
        base-config: default


bucket4j:
  capacity: 100
