app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 1m
  database-access-type: jpa

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
      exposure:
        include: [ "prometheus", "health", "info" ]
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: "/swagger-ui"
