app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 1m
  database-access-type: jdbc

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: "/swagger-ui"

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 100ms
        enable-exponential-backoff: true
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.reactive.function.client.WebClientRequestException
    instances:
      updatesPost:
        base-config: default
      fetchRepo:
        base-config: default
      fetchCommitsSince:
        base-config: default
      fetchPullRequestsSince:
        base-config: default
      fetchQuestion:
        base-config: default
      fetchAnswersSince:
        base-config: default


bucket4j:
  capacity: 100
