app:
  telegram-token: ${TELEGRAM_TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  config:
    import: optional:file:.env[.properties]
  kafka:
    topic: "updates-topic"
    bootstrap-servers: "localhost:29092"
    consumer:
      group-id: "demo-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: edu.java.bot.dto.LinkUpdateRequest

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: "/swagger-ui"

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.reactive.function.client.WebClientRequestException

bucket4j:
  capacity: 100
