app:
  telegram-token: ${TELEGRAM_TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  config:
    import: optional:file:.env[.properties]

server:
  port: 8090

management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
      exposure:
        include: [ "prometheus", "health", "info" ]
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: "/swagger-ui"
